---
image:
  blockscout:
    repository: blockscout/blockscout
    tag: latest #v4.0.0-beta #v4.1.5-beta #e3d5778 #ee574148b #v4.1.5-beta #v4.0.0-beta #e3d5778
    pullPolicy: IfNotPresent

postgresql:
  postgresqlDatabase: postgres
  postgresqlUsername: postgres
  postgresqlPassword: postgres
  initdbUser: postgres
  initdbPassword: postgres
  enabled: true

blockscout: # cpu dependent
  resources:
    cpuLimit: 0.7
    cpuRequest: 0.5
    memLimit: "2G"
    memRequest: "1G"
  port: 4000
  database_url: "ecto://postgres:postgres@blockscout-postgresql/postgres?ssl=false"
  postgres_password: postgres
  postgres_user: postgres
  network: quorum
  subnetwork: consensys
  chain_id: 1337
  coin: eth
  ethereum_jsonrpc_variant: geth
  ethereum_jsonrpc_transport: http
  ethereum_jsonrpc_endpoint: "goquorum-node-validator-4" # service name to be used
  secret_key_base: "VTIB3uHDNbvrY0+60ZWgUoUBKDn9ppLR8MI4CpRz4/qLyEFs54ktJfaNT6Z221" # change me please



  PGPASSWORD='u78REleu19' psql -U postgres -d postgres -c "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = 'postgres' AND pid <> pg_backend_pid();"


  psql -U postgres -h my-postgresql-0 -d postgres -c "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = 'your_database_name' AND pid <> pg_backend_pid();"


PGPASSWORD='u78REleu19' psql -U postgres -h my-postgresql.eval-q-10.svc.cluster.local -d postgres -c "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = 'postgres' AND pid <> pg_backend_pid();"


PGPASSWORD='u78REleu19' psql -U postgres -h my-postgresql.eval-q-10.svc.cluster.local -d template1 -c "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = 'postgres' AND pid <> pg_backend_pid();"


export PGPASSWORD='u78REleu19' 

PGPASSWORD='u78REleu19' psql -U postgres -h my-postgresql.eval-q-10.svc.cluster.local -d template1 -c "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = 'postgres' AND pid <> pg_backend_pid();"

PGPASSWORD='u78REleu19' psql -U postgres -h my-postgresql.eval-q-10.svc.cluster.local -d template1 -c "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = 'postgres' AND pid <> pg_backend_pid();"



export PGPASSWORD='u78REleu19'
PGPASSWORD='u78REleu19' psql -U postgres -h my-postgresql.eval-q-10.svc.cluster.local -d template1 -c "DROP DATABASE postgres;"

export PGPASSWORD='u78REleu19'
PGPASSWORD='u78REleu19' psql -U postgres -h my-postgresql.eval-q-10.svc.cluster.local -d template1 -c "CREATE DATABASE postgres;" && mix do ecto.create, ecto.migrate


kubectl exec -it <application-pod-name> -n <application-namespace> -- curl my-postgresql.eval-q-10.svc.cluster.local:5432

PGPASSWORD='u78REleu19' psql -U postgres -h my-postgresql.eval-q-10.svc.cluster.local -d postgres -c "SELECT 1;"

PGPASSWORD='u78REleu19' psql -U postgres -h my-postgresql.eval-q-10.svc.cluster.local -d template1 -c "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = 'postgres' AND state = 'idle';"


PGPASSWORD='u78REleu19' psql -U postgres -h my-postgresql.eval-q-10.svc.cluster.local -d template1 -c "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = 'postgres' AND pid <> pg_backend_pid();" && PGPASSWORD='u78REleu19' psql -U postgres -h my-postgresql.eval-q-10.svc.cluster.local -d template1 -c "DROP DATABASE postgres;"
PGPASSWORD='u78REleu19' psql -U postgres -h my-postgresql.eval-q-10.svc.cluster.local -d template1 -c "CREATE DATABASE postgres;" && mix do ecto.create, ecto.migrate