apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-my-postgresql-0
  namespace: eval-q-07
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp2