global:
  postgresql:
    postgresqlDatabase: postgres
    postgresqlUsername: postgres
    postgresqlPassword: postgres

primary:
  service:
    port: 5432
  persistence:
    enabled: true
    size: 50Gi
  resources:
    requests:
      memory: "4Gi"
      cpu: "2"
    limits:
      memory: "8Gi"
      cpu: "4"

pgHbaConfiguration: |
  host all all 0.0.0.0/0 md5

replication:
  enabled: false

postgresqlExtendedConf:
  max_connections: 1000
  shared_buffers: "2GB"
  effective_cache_size: "6GB"
  maintenance_work_mem: "1GB"
  checkpoint_completion_target: 0.9
  wal_buffers: "16MB"
  default_statistics_target: 100
  random_page_cost: 1.1
  effective_io_concurrency: 200
  work_mem: "50MB"
  min_wal_size: "1GB"
  max_wal_size: "4GB"
  max_worker_processes: 8
  max_parallel_workers_per_gather: 4
  max_parallel_workers: 8
  max_parallel_maintenance_workers: 4


